apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- octopub-audits-mysql.yaml
- octopub-ingress.yaml

configMapGenerator:
  - name: audit-service-env-vars
    env: variables.properties

generatorOptions:
  disableNameSuffixHash: true