apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
secretGenerator:
  - name: database-credentials
    envs:
    - secrets.properties

generatorOptions:
  disableNameSuffixHash: true