apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octopub-ingress-frontend
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  octopub-frontend-cluster-ip
            port:
              name: http-web