apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octopub-ingress-products
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host:
    http:
      paths:
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: octopub-productservice-cluster-ip
            port:
              name: http-product
      - path: /health/products
        pathType: Prefix
        backend:
          service:
            name: octopub-productservice-cluster-ip
            port:
              name: http-product
